// Serves a viewport-appropriate WebP where variants exist, falling back to the
// original file. Same pattern as the Markwicks build.
//
// Variants are generated by scripts/generate-images.mjs, which skips widths
// larger than the source rather than upscaling. The component therefore cannot
// assume every width exists - it consults the manifest the generator writes.
// Advertising a width that was never produced makes the browser request a file
// that is not there.

import MANIFEST from '../data/image-manifest.json'

function entryFor(src) {
  const m = /^\/images\/(.+)\.(jpe?g|png)$/i.exec(src || '')
  return m && MANIFEST[m[1]] ? { base: m[1], ...MANIFEST[m[1]] } : null
}

export default function Img({ src, alt, sizes = '100vw', className, ...rest }) {
  const entry = entryFor(src)

  // Intrinsic dimensions give the browser an aspect ratio before the bytes
  // arrive, so the box is reserved without depending on the stylesheet.
  const dims =
    entry?.w && entry?.h && rest.width === undefined && rest.height === undefined
      ? { width: entry.w, height: entry.h }
      : {}

  if (!entry?.widths?.length) {
    return <img src={src} alt={alt} className={className} {...dims} {...rest} />
  }

  const srcSet = entry.widths.map((w) => `/images/r/${entry.base}-${w}.webp ${w}w`).join(', ')

  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={sizes} />
      <img src={src} alt={alt} className={className} {...dims} {...rest} />
    </picture>
  )
}
